require 'hoe'
require './lib/webget/version.rb'

Hoe.spec 'webget' do

  self.version = Webget::VERSION

  self.summary = 'webget gem - a web (go get) crawler incl. web cache'
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/webclient' }

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['webclient', '>= 0.2.0'],
    ['csvreader', '>= 1.2.4'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
